### ISSUE TITLE
Error ! 

### ISSUE THREAD

**Issue by stenote** [dennydai/docker-letsencrypt#4]
```
Registering account...Traceback (most recent call last):
  File "/root/docker-letsencrypt/acme_tiny.py", line 197, in <module>
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir)
  File "/root/docker-letsencrypt/acme_tiny.py", line 94, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]",
  "status": 400
}
```

**Comment by DennyDai** [comment]
Sorry, I have stopped providing support for this repo since let's encrypt change its program's name to certbot. You may need to find another way to get your cert. Sorry for that.

**Comment by stenote** [comment]
Roger that, thanks a lot !

**Comment by ghost** [comment]
It is better to add 'deprecated' claim into README.md.
